<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-03-07T16:23:27Z" name="Roicians" finished-at="2020-03-07T16:24:10Z" duration-ms="42709">
    <groups>
    </groups>
    <test started-at="2020-03-07T16:23:27Z" name="Hybrid Framework" finished-at="2020-03-07T16:24:10Z" duration-ms="42709">
      <class name="roicians.testcases.Contact_ustest">
        <test-method is-config="true" signature="setprop()[pri:0, instance:roicians.testcases.Contact_ustest@318ba8c8]" started-at="2020-03-07T16:23:27Z" name="setprop" finished-at="2020-03-07T16:23:45Z" duration-ms="17317" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setprop -->
        <test-method signature="titlevalidation()[pri:1, instance:roicians.testcases.Contact_ustest@318ba8c8]" started-at="2020-03-07T16:23:45Z" name="titlevalidation" finished-at="2020-03-07T16:23:45Z" duration-ms="12" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Contact_us] but found [Contact Us | Roicians]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Contact_us] but found [Contact Us | Roicians]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at roicians.testcases.Contact_ustest.titlevalidation(Contact_ustest.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titlevalidation -->
        <test-method is-config="true" signature="close()[pri:0, instance:roicians.testcases.Contact_ustest@318ba8c8]" started-at="2020-03-07T16:23:45Z" name="close" finished-at="2020-03-07T16:23:46Z" duration-ms="1395" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="setprop()[pri:0, instance:roicians.testcases.Contact_ustest@318ba8c8]" started-at="2020-03-07T16:23:46Z" name="setprop" finished-at="2020-03-07T16:23:56Z" duration-ms="10137" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setprop -->
        <test-method signature="typevalidname()[pri:2, instance:roicians.testcases.Contact_ustest@318ba8c8]" started-at="2020-03-07T16:23:56Z" name="typevalidname" finished-at="2020-03-07T16:23:56Z" duration-ms="103" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- typevalidname -->
        <test-method is-config="true" signature="close()[pri:0, instance:roicians.testcases.Contact_ustest@318ba8c8]" started-at="2020-03-07T16:23:56Z" name="close" finished-at="2020-03-07T16:23:57Z" duration-ms="1326" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="setprop()[pri:0, instance:roicians.testcases.Contact_ustest@318ba8c8]" started-at="2020-03-07T16:23:58Z" name="setprop" finished-at="2020-03-07T16:24:08Z" duration-ms="10958" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setprop -->
        <test-method signature="typevalidemail()[pri:3, instance:roicians.testcases.Contact_ustest@318ba8c8]" started-at="2020-03-07T16:24:08Z" name="typevalidemail" finished-at="2020-03-07T16:24:09Z" duration-ms="111" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- typevalidemail -->
        <test-method is-config="true" signature="close()[pri:0, instance:roicians.testcases.Contact_ustest@318ba8c8]" started-at="2020-03-07T16:24:09Z" name="close" finished-at="2020-03-07T16:24:10Z" duration-ms="1309" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- roicians.testcases.Contact_ustest -->
    </test> <!-- Hybrid Framework -->
  </suite> <!-- Roicians -->
</testng-results>
